export const LOADING_SCREEN_DURATION = 3;
export const LOADING_SCREEN_EXIT_DURATION = 0.8;

export const HERO_SODIUM_ANIMATION_DELAY = LOADING_SCREEN_DURATION + 0.5;
export const HERO_SODIUM_ANIMATION_DURATION = 0.8;
export const HERO_FADE_IN_DELAY =
  HERO_SODIUM_ANIMATION_DELAY + HERO_SODIUM_ANIMATION_DURATION + 0.2;
