export const meta = {
  author: {
    name: "Nur Alam",
    label: "Front-End Developer",
    username: "nuralam123",
  },
  site: {
    title: "Nur Alam",
    description:
      "Hi! I am Nur, a Frontend Developer living in Dhaka, Bangladesh. I love creating creative, soothing websites",
    bannerImage: "/natrium.png",
    url: "https://nuralam.vercel.app",
    keywords: [
      "web development",
      "portfolio",
      "nur alam",
      "natrium",
      "frontend",
      "developer",
      "frontend developer",
      "frontend engineer",
      "nur",
      "na",
      "sodium",
      "web",
      "design",
      "web design",
      "alam",
      "11",
      "eleven",
      "11th",
    ],
    language: "en",
    charset: "UTF-8",
  },
};
